1-helloworld/pom.xml, 1-helloworld/src/main/java/com/example/appengine/gettingstartedjava/helloworld/HelloServlet.java
This should address the current issue in https://github.com/GoogleCloudPlatform/getting-started-java/pull/2 where an older version of the gcloud maven plugin cannot find the gcloud sdk.
=> Update maven plugin to 2.0.9.88.v20151125

README.md, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/RootServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/auth/LoginServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/auth/LogoutServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/auth/Oauth2CallbackServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/basicactions/CreateBookServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/basicactions/DeleteBookServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/basicactions/ListBookServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/basicactions/ListByUserServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/basicactions/ReadBookServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/basicactions/UpdateBookServlet.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/daos/BookDao.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/daos/CloudSqlDao.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/daos/DatastoreDao.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/objects/Book.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/objects/Result.java, bookshelf/src/main/java/com/example/appengine/gettingstartedjava/util/CloudStorageHelper.java, bookshelf/src/main/webapp/WEB-INF/appengine-web.xml, bookshelf/src/main/webapp/WEB-INF/datastore-indexes.xml, bookshelf/src/main/webapp/WEB-INF/web.xml, bookshelf/src/main/webapp/base.jsp, bookshelf/src/main/webapp/form.jsp, bookshelf/src/main/webapp/list.jsp, bookshelf/src/main/webapp/view.jsp, helloworld/pom.xml
Next submit will be more fine grained.
=> brain dead - doc tags

.gitignore, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/Oauth2CallbackServlet.java, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/CreateBookServlet.java, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/UpdateBookServlet.java, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/daos/CloudSqlDao.java, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/daos/DatastoreDao.java, bookshelf/src/main/webapp/form.jsp, java-repo-tools/google-checks.xml
We have developers run the sample without doing any configuration. It's
not a great experience if the app seems broken when they create a book
and try to include an image.
I only hide the element since the Create and Update servlets expect the
"file" property to be populated (even if it's empty string).
We should consider doing the same for the login button and "my books"
button if the client ID for OAuth2 is not set.
=> Hide image upload when no Cloud Storage config.

bookshelf/makeBookshelf
This is created by default when checking the box in the GUI console page
when creating an instance with "Allow HTTP" checked, but it is not
created when creating an instance tagged "http-server" from the command
line.
=> Create firewall rule to allow port 80 access.

bookshelf/makeBookshelf
Also, I noticed the start-up script was failing for the multi-instance
demo due to the BUCKET metadata being unavailable, so I added that
metadata to the template.
=> Clean-up firewall rule.

README.md
The link https://cloud.google.com/java/getting-started/ still 404s. This changes the link to the main https://cloud.google.com/java/ landing page.
Fixes https://github.com/GoogleCloudPlatform/getting-started-java/issues/10.
=> Fix broken link to Java getting started.

bookshelf/pom.xml, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/daos/DatastoreDao.java, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/util/CloudStorageHelper.java, bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/util/DatastoreSessionFilter.java
gcloud-java renamed it's group id and changed it's packaging from com.google.gcloud to com.google.cloud in the latest release.  This PR updates bookshelf to pick up those changes.
=> Update gcloud-java dependency and package names

.travis.yml, helloworld-jsp/src/main/java/org/example/appengine/hello/HelloInfo.java, helloworld-servlet/pom.xml, helloworld-springboot/pom.xml, helloworld-springboot/src/main/java/com/example/java/gettingstarted/HelloworldApplication.java, helloworld-springboot/src/test/java/com/example/java/gettingstarted/HelloworldApplicationTests.java, java-repo-tools/README.md, pom.xml
Add lint checks to Java getting started samples.
Sorry for the extra commits. ☹ I had to merge histories to keep `java-repo-tools` subtree in sync without causing every change to be a conflict.
=> Add lint checks to Java getting started samples.

helloworld-servlet/README.md
Using the `gcloud:run` plugin fails because it is looking for
`appengine-web.xml`.
```
$ mvn gcloud:run
...
[ERROR]
com.google.apphosting.utils.config.AppEngineConfigException: Could not locate /usr/local/google/home/swast/src/getting-started-java/helloworld-servlet/target/helloworld-servlet-1.0-SNAPSHOT/WEB-INF/appengine-web.xml
at com.google.apphosting.utils.config.AppEngineWebXmlReader.getInputStream(AppEngineWebXmlReader.java:141)
at com.google.apphosting.utils.config.AppEngineWebXmlReader.readAppEngineWebXml(AppEngineWebXmlReader.java:75)
at com.google.appengine.gcloudapp.AbstractGcloudMojo.getAppEngineWebXml(AbstractGcloudMojo.java:576)
at com.google.appengine.gcloudapp.AbstractGcloudMojo.executeAppCfgStagingCommand(AbstractGcloudMojo.java:663)
at …
```
=> Recommend `jetty:run-exploded` for local Hello World.

helloworld-jsp/README.md
I get an exception when useing `mvn gcloud:run` (No appengine-web.xml)
=> helloworld-jsp needs to use jetty plugin local dev

helloworld-springboot/pom.xml
Running `mvn gcloud:deploy` on the pristine helloworld-springboot project would fail with:
```
...
[INFO] Updating service [default]...
[INFO]                              
[INFO] Updating service [default]...failed.
[INFO] ERROR: (gcloud.preview.app.deploy) Error Response: [13] Timed out when starting VMs.  It's possible that the application code is unhealthy.  (0/1 ready, 1 still deploying).
[ERROR] Error: gcloud app command with exit code : 1
```
I eventually found in the gcloud log files that the main manifest attribute was missing.
Can see similar errors with `mvn package` followed by `java -jar target/helloworld-springboot-0.0.1-SNAPSHOT.jar'
=> Fix failing gcloud:deploy error due to lack of an executable jar file.

.travis.yml, java-repo-tools/scripts/test-localhost.sh, travis.sh
Run the local servers and verify they respond with code 200 to the "/"
path.
Note: bookshelf does not yet run in Travis, since we'll need to set up
client secrets credentials.
=> Add localhost tests to Travis.

bookshelf/6-gce/gce/startup-script.sh
There was an update to shellcheck, so Travis started failing with error [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164). The `cd` command can fail, so it was looking for proper error handling of this case.
It appears to me that most of the other commands can also fail in this
startup script, and we don't really want to continue if any of them does
fail, so I add the `set -e` option. This exits the script if there is an
error and also silences this shellcheck error.
@lesv PTAL
=> Exit script on errors.

helloworld-compat/build.gradle, helloworld-jsp/build.gradle, helloworld-servlet/build.gradle
Now a user can cleanly uncomment the the Sonatype snapshot repo block rather than having to create a separate declaration. Saves a few seconds effort but the resulting files look better, too.
=> Typos + import formatting improvements

bookshelf/6-gce/gce/startup-script.sh
the command 
> service jetty status
when jetty is not running returns an exit code of "3" which will cause the startup script to exit prematurely before jetty has started. 
Jan 12 03:31:25 my-app-instance startup-script: INFO startup-script: ● jetty.service - SYSV: Jetty 9 webserver
Jan 12 03:31:25 my-app-instance startup-script: INFO startup-script:    Loaded: loaded (/etc/init.d/jetty)
Jan 12 03:31:25 my-app-instance startup-script: INFO startup-script:    Active: inactive (dead)
Jan 12 03:32:26 my-app-instance startup-script: INFO startup-script: Return code 3.
This change just removes that command and just starts jetty.
=> remove "service jetty status" from startup script.

helloworld-servlet/build.gradle
Gretty host property is deprecated, please use httpPort instead
http://akhikhl.github.io/gretty-doc/Gretty-configuration.html
=> Fix deprecated host parameter

bookshelf/6-gce/makeBookshelf
Context: https://github.com/GoogleCloudPlatform/golang-samples/pull/205/files
(side note: I don't see where this create named ports, perhaps you're not using them?)
=> Fix gcloud commands for GCE deployment

bookshelf-standard/2-structured-data/src/main/webapp/WEB-INF/web.xml, bookshelf-standard/3-binary-data/src/main/webapp/WEB-INF/web.xml, bookshelf-standard/4-auth/src/main/webapp/WEB-INF/web.xml, bookshelf-standard/5-logging/src/main/webapp/WEB-INF/web.xml, bookshelf-standard/pom.xml, pom.xml
We hit a couple of issues when [importing the _bookshelf-standard_ examples into Eclipse](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1557):
1. The _bookshelf-standard_ `web.xml` files are missing the required schema details and claim to require Servlet API 3.0, whereas App Engine Standard only support 2.5 at the moment.
2. M2Eclipse needs some help to deal with using _errorprone_.
3. M2Eclipse doesn't ([currently](https://bugs.eclipse.org/bugs/show_bug.cgi?id=514577)) support using the `maven.war.filteringDeploymentDescriptors` user property to control filtering of the `web.xml`.  It turns out that the `maven-war-plugin` 3.0 has removed this user property.
=> Make bookshelf-standard examples import into Eclipse

bookshelf/pom.xml, helloworld-jsp/pom.xml, helloworld-servlet/pom.xml
Quickstart tutorial is failing: https://cloud.google.com/appengine/docs/flexible/java/quickstart
Updated to latest Jetty Maven plugin
=> Fix jetty version

bookshelf/optional-container-engine/bookshelf-frontend.yaml
I didn't realize the project should be packaged with `-DprojectID`.
Doing so eliminates the need for this GCLOUD_PROJECT env var
I added in the last PR.
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
=> gke: GCLOUD_PROJECT env is not necessary

appengine-standard-java8/helloworld/pom.xml
Packaging war is required for plugins to inject in the correct lifecycle phases.
=> Packaging should be war

bookshelf/6-gce/gce/startup-script.sh
Fails in installing on Debian-8 without explicitly setting the backport type.
https://packages.debian.org/jessie-backports/openjdk-8-jdk
=> use jessie-backport for openjdk install

bookshelf/6-gce/makeBookshelf
Increasing memory size from f1-micro to g1-small as frequent failures due to insufficient memory errors. 
- Removed white space and changed use of deprecated `--image` parameter for `--image-family` and `--image-project`
=> Increasing machine size from f1-micro to g1-small.

bookshelf/6-gce/README.md, bookshelf/6-gce/pom.xml
The current instruction at https://cloud.google.com/java/tutorials/bookshelf-on-compute-engine doesn't expect/suggest the user should use the project-id as the bucket name. So I updated the value of the `bookshelf.bucket` to be `myBucketName` instead.
=> Modified bookshelf.bucket property to use myBucketName instead of using projectId

bookshelf-standard/4-auth/src/main/java/com/example/getstarted/auth/LoginServlet.java
Move the top region tag so all the imported classes are not displayed in documentation.
=> Region tag modification for documentation

appengine-standard-java8/helloworld-gae-javasdk-tools/pom.xml
Otherwise, the line prefix will be included in the rendered output, for example "<!--".  specifying silent means that everything will be excluded.
=> Add "silent" param to START_EXCLUDE

appengine-standard-java8/springboot-appengine-standard/README.md, appengine-standard-java8/springboot-appengine-standard/src/main/webapp/WEB-INF/appengine-web.xml
appengine-web.xml syntax changed so logging property is not set correctly.
Please refer to https://cloud.google.com/appengine/docs/standard/java/config/appref#syntax
=> Proper way to set up logging property in appengine-web.xml

bookshelf/2-structured-data/pom.xml
Fix reading of interpolated property ${bookshelf.storageType} in bookshelf/2-structured-data web.xml.
Checked the [param value string](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf/2-structured-data/src/main/java/com/example/getstarted/basicactions/ListBookServlet.java#L45) for "bookshelf.storageType" in ListBookServlet.init and it was the literal "${bookshelf.storageType}". 
Adding the maven-war-plugin allows interpolated property values in web.xml. 
Tested with `mvn jetty:run-exploded`.
Verified with `mvn appengine:deploy'. See [dzlier-work.appspot.com](https://dzlier-work.appspot.com/)
=> Fix reading of interpolated property in bookshelf web.xml

.kokoro/presubmit.cfg, .kokoro/tests/diff_tests.sh
Enables Kokoro presubmit tests to only `mvn:verify` project directories which have changed from the master branch, instead of running all tests.
Copied from the same [change in java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1008)
=> Add diff_tests.sh to getting-started-java

appengine-standard-java8/helloworld/build.gradle, flexible/tomcat/helloworld/build.gradle, helloworld-jsp/build.gradle, helloworld-servlet/build.gradle
limit current gradle plugin to 1.+ (instead of +), so we can gracefully update to 2.0 (or 2.+) when that goes GA.
=> Use latest 1.X release for gradle plugin

appengine-standard-java8/kotlin-springboot-appengine-standard/pom.xml
Periodic tests are failing for getting-started-java because the kotlin-springboot-appengine-standard project fails to deploy. This is because the kotlin reflect library is needed as a dependency - when deploying locally, I was getting ClassNotFoundExceptions on kotlin's `KClasses`
Also kotlin-stdlib-jre8 is deprecated and should be replaced with kotlin-stdlib-jdk8.
=> Fix kotlin-springboot-appengine-standard deploy error in periodic tests.

.github/CODEOWNERS
Anyone else who should be added to particular sub projects is welcome to add their names as well, using other CODEOWNERS files as [examples](https://github.com/googleapis/google-cloud-python/blob/master/.github/CODEOWNERS).
=> Add CODEOWNERS file to automatically assign reviews to dzlier.

bookshelf-standard/2-structured-data/pom.xml, bookshelf-standard/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf-standard/3-binary-data/pom.xml, bookshelf-standard/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf-standard/4-auth/pom.xml, bookshelf-standard/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf-standard/5-logging/pom.xml, bookshelf-standard/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf-standard/pom.xml, bookshelf/2-structured-data/pom.xml, bookshelf/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf/3-binary-data/pom.xml, bookshelf/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf/4-auth/pom.xml, bookshelf/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf/5-logging/pom.xml, bookshelf/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf/6-gce/pom.xml, bookshelf/6-gce/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java, bookshelf/optional-kubernetes-engine/pom.xml, bookshelf/optional-kubernetes-engine/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
Fusion period tests are failing due to a deprecated constructor of `WebDriverWait`.
Along with the update, Guava also needed to be updated to properly support the `until` function in `FluentWait`.
=> Fix selenium errors in periodic tests.

gce/makeProject, gce/pom.xml, gce/scripts/startup-script.sh
Previously the getting started java workflow required cloning into a personal source repo and uploading a jar to storage.
This change enables removing both those dependencies, instead allowing the user to build and run the server directly from GoogleCloudPlatform/getting-started-java from Cloud Shell.
=> Update GCE Getting Started project to build directly from base repo.

pom.xml
It looks like the deletions from a recent PR didn't fully get excised
from the root pom.  This removes the remaining reference.
PR where the files where deleted:
https://github.com/GoogleCloudPlatform/getting-started-java/pull/440
=> fix root pom

renovate.json
"rebaseStalePrs" has been deprecated:
https://docs.renovatebot.com/configuration-options/#rebasewhen
=> Update renovate to use new "rebaseWhen" flag.

gce/scripts/startup-script.sh
Per this post: https://central.sonatype.org/articles/2019/Jul/15/central-http-deprecation-update/
http://central.maven.org is no longer supportd. https://repo1.maven.org (note the https requirement) will continue to be supported. I ran into this while setting up my own GCP project and have confirmed that the script works with this change (see https://github.com/jalexanderqed/gcloud-website/blob/master/scripts/startup-script.sh).
=> Fix Maven URL in startup-script.sh
