- bookshelf/src/main/java/com/example/appengine/gettingstartedjava/daos/CloudSqlDao.java
- bookshelf/src/main/java/com/example/appengine/gettingstartedjava/daos/DatastoreDao.java
- bookshelf/src/main/java/com/example/appengine/gettingstartedjava/objects/Book.java
- bookshelf/src/main/webapp/WEB-INF/web.xml
and fix bug in web.xml
@shun-fan FYI
> some fine grain tags

- bookshelf/pom.xml
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/LoginServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/LogoutServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/Oauth2CallbackServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/CreateBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/ListBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/ListByUserServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/ReadBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/UpdateBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/util/DatastoreHttpServlet.java
fixes #18 
uses datastore to prevent token spoofing from cookies
> Datastore sessions

- helloworld-servlet/src/main/appengine/app.yaml
1. Exclude runtime_config
2. Exclude manual scaling
3. move beta_settings
@shun-fan
> Exclude a bit more.

- README.md
- helloworld-springboot/README.md
- helloworld-springboot/pom.xml
- helloworld-springboot/src/main/appengine/app.yaml
- helloworld-springboot/src/main/java/com/example/java/gettingstarted/HelloworldApplication.java
- helloworld-springboot/src/test/java/com/example/java/gettingstarted/HelloworldApplicationTests.java
A quick example on Spring Boot Helloworld with App Engine MVM.
> Spring Boot example

- helloworld-servlet/src/main/appengine/app.yaml
Change the order so that it looks a bit better in the docs.
> Fix app yaml

- helloworld-jsp/pom.xml
- helloworld-servlet/pom.xml
- helloworld-servlet/src/main/appengine/app.yaml
1. remove java_quickstart from helloWorld-servlet
2. Add space in pom for helloworld-servlet
3. Take up Ray’s comment and rename helloworld-jsp
> Rid the world of java_quickstart

- helloworld-servlet/pom.xml
> Smaller pom

- helloworld-servlet/pom.xml
> Add comments to the pom

- bookshelf/pom.xml
- helloworld-servlet/pom.xml
> minor updates to pom's

- bookshelf/index.yaml
- bookshelf/pom.xml
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/LoginServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/Oauth2CallbackServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/ListBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/daos/CloudSqlDao.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/util/CloudStorageHelper.java
- bookshelf/src/main/webapp/WEB-INF/bookshelf.properties
- bookshelf/src/main/webapp/WEB-INF/index.yaml
1. move from env vars in app.yam to bookshelf.properties
> Switch from envVars to Properties

- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/daos/DatastoreDao.java
IntelliJ suggested refactoring common code, so I created
entititesToBooks()
> Additional comments

- bookshelf/pom.xml
- bookshelf/src/main/appengine/app.yaml
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/daos/DatastoreDao.java
1. comment and move stuff around in app.yaml
2. more comments in pom.xml
3. Minor refactor of DatastoreDao
> minor refactor of DatastoreDao

- bookshelf/pom.xml
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/Oauth2CallbackServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/util/DatastoreSessionFilter.java
- helloworld-jsp/pom.xml
- helloworld-servlet/pom.xml
- helloworld-springboot/pom.xml
- pom.xml
1. Update the version of the gcloud-maven plugin
2. Move / add comments
3. rename somethings to flex
4. Don’t use DEPRECATED scope and reduce the access to what we need.
> versions, comments, flex, scopes

- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/LoginServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/auth/LogoutFilter.java
1. Another place scopes are listed.
2. Fix comments.
> fix scopes and add comments

- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/CreateBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/ListBookServlet.java
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/UpdateBookServlet.java
- bookshelf/src/main/webapp/base.jsp
Also, moves `isSomeFeatureConfigured` population to `ListBookServlet`.
It seems to me that we might hit cases where the first servlet to get
hit by an instance is not `ListBookServlet`, but this seems rare and all
the other configuration is loaded here.
Replaces https://github.com/GoogleCloudPlatform/getting-started-java/pull/64
CC @shun-fan
> Hide login when client id and secret are not set.

- bookshelf/makeBookshelf
- bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/HealthServlet.java
Also, I got a warning that `--group` is deprecated, so I changed to `--instance-group`.
> Add health check for GCE.

- bookshelf/pom.xml
See https://github.com/GoogleCloudPlatform/java-docs-samples/issues/150.
> Update gcloud-java to 0.1.7.

- helloworld-springboot/README.md
This sample is linked to from https://cloud.google.com/java/
> Add more instructions for Spring Boot Hello World.

- java-repo-tools/README.md
- java-repo-tools/codecov.yml
- java-repo-tools/pom.xml
- java-repo-tools/test/pom.xml
- java-repo-tools/test/src/main/java/com/google/cloud/samples/test/App.java
- java-repo-tools/test/src/test/java/com/google/cloud/samples/test/AppTest.java
> update java repo tools

- helloworld-compat/src/main/java/com/example/appengine/helloworld/HelloServlet.java
Eventually these will change to all be in one group per the new
guidelines, but I haven't taught checkstyle that, yet.
@lesv FYI
> Sort imports to match checkstyle order.

- helloworld-compat/build.gradle
- helloworld-jsp/build.gradle
- helloworld-servlet/build.gradle
There is no longer a model in the gradle plugin.
> remove model

- bookshelf/README.md
Renaming some APIs to Stackdriver brand
> Stackdriver product rename

- pom.xml
Forgot to remove it from pom.xml
> remove helloworld-compat

- bookshelf/6-gce/gce/startup-script.sh
- bookshelf/6-gce/pom.xml
Jetty download link update
Artifact name update in pom.xml
Jetty service startup fix
> Fixing startup script

- helloworld-springboot/README.md
- helloworld-springboot/src/main/appengine/app.yaml
- helloworld-springboot/src/main/java/com/example/java/gettingstarted/HelloworldApplication.java
- point to `app.yaml`
- note that deployment requires the new maven plugin
> Add some missing information for Flex deployment

- bookshelf-standard/2-structured-data/README.md
- bookshelf-standard/2-structured-data/pom.xml
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/basicactions/CreateBookServlet.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/basicactions/DeleteBookServlet.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/basicactions/ListBookServlet.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/basicactions/ReadBookServlet.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/basicactions/UpdateBookServlet.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/daos/BookDao.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/daos/CloudSqlDao.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/daos/DatastoreDao.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/objects/Book.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/objects/Result.java
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/util/DatastoreSessionFilter.java
- bookshelf-standard/2-structured-data/src/main/webapp/WEB-INF/appengine-web.xml
- bookshelf-standard/2-structured-data/src/main/webapp/WEB-INF/web.xml
- bookshelf-standard/2-structured-data/src/main/webapp/base.jsp
- bookshelf-standard/2-structured-data/src/main/webapp/form.jsp
- bookshelf-standard/2-structured-data/src/main/webapp/list.jsp
- bookshelf-standard/2-structured-data/src/main/webapp/view.jsp
An adaptation of the flex one.
Tested with devserver + cloudsql, appengine + cloudsql, devserver + datastore, appengine + datastore.
> GAE standard bookshelf - step 2

- .gitignore
- helloworld-jsp/README.md
- helloworld-servlet/README.md
> IntelliJ IDEA

- .travis.yml
- README.md
- bookshelf-standard/2-structured-data/pom.xml
- bookshelf-standard/2-structured-data/src/main/java/com/example/getstarted/util/DatastoreSessionFilter.java
- bookshelf-standard/2-structured-data/src/test/java/com/example/getstarted/basicactions/ListBookServletIT.java
- bookshelf-standard/3-binary-data/pom.xml
- bookshelf-standard/3-binary-data/src/main/java/com/example/getstarted/util/DatastoreSessionFilter.java
- bookshelf-standard/4-auth/pom.xml
- bookshelf-standard/4-auth/src/main/java/com/example/getstarted/daos/DatastoreDao.java
- bookshelf-standard/4-auth/src/main/java/com/example/getstarted/util/DatastoreSessionFilter.java
- bookshelf-standard/5-logging/pom.xml
- bookshelf-standard/5-logging/src/main/java/com/example/getstarted/daos/DatastoreDao.java
- bookshelf-standard/5-logging/src/main/java/com/example/getstarted/util/DatastoreSessionFilter.java
- bookshelf-standard/pom.xml
- bookshelf/2-structured-data/pom.xml
- bookshelf/3-binary-data/pom.xml
- bookshelf/4-auth/pom.xml
- bookshelf/5-logging/pom.xml
- bookshelf/6-gce/pom.xml
- bookshelf/optional-container-engine/pom.xml
- bookshelf/pom.xml
- circle.yml
- helloworld-jsp/pom.xml
- helloworld-servlet/pom.xml
- helloworld-springboot/pom.xml
- pom.xml
- travis.sh
Just a test for now to make sure travis passes...
> Initial selenium test.

- circle.yml
More trouble managing than it's worth.
> Remove cache directory.

- .travis.yml
- README.md
> Fix circleci link.

- bookshelf-standard/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/3-binary-data/README.md
- bookshelf-standard/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/4-auth/README.md
- bookshelf-standard/4-auth/pom.xml
- bookshelf-standard/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/5-logging/README.md
- bookshelf-standard/5-logging/pom.xml
- bookshelf-standard/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- travis.sh
> Add selenium tests for gae-std#3,4

- bookshelf-standard/2-structured-data/jenkins.sh
- bookshelf-standard/2-structured-data/pom.xml
- bookshelf-standard/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/3-binary-data/pom.xml
- bookshelf-standard/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/4-auth/pom.xml
- bookshelf-standard/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/5-logging/pom.xml
- bookshelf-standard/5-logging/src/main/webapp/WEB-INF/datastore-indexes.xml
- bookshelf-standard/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/pom.xml
- jenkins.sh
This creates a jenkins script to be run nightly, which actually deploys the std app and runs the selenium tests on them. Since the app is deployed, we're not able to fully test the auth flow without a Real Account, but we do as much as we can.
This also deploys to runtime:java8, after deploying to normal GAE std.
> Deployment tests for Jenkins, Java7,8

- bookshelf-standard/3-binary-data/jenkins.sh
- bookshelf-standard/4-auth/jenkins.sh
- bookshelf-standard/5-logging/jenkins.sh
- bookshelf/2-structured-data/README.md
- bookshelf/2-structured-data/jenkins.sh
- bookshelf/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/3-binary-data/README.md
- bookshelf/3-binary-data/jenkins.sh
- bookshelf/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/4-auth/README.md
- bookshelf/4-auth/jenkins.sh
- bookshelf/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/5-logging/README.md
- bookshelf/5-logging/jenkins.sh
- bookshelf/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/6-gce/README.md
Complete with selenium integration tests against them!
> Jenkins deployment tests for flex

- bookshelf-standard/3-binary-data/jenkins.sh
- bookshelf-standard/4-auth/jenkins.sh
- bookshelf-standard/5-logging/jenkins.sh
Also, use the service account so it can actually deploy.
> Add jenkins tests for other steps.

- bookshelf/optional-container-engine/pom.xml
> add namespace

- bookshelf-standard/3-binary-data/README.md
- bookshelf-standard/4-auth/README.md
- bookshelf-standard/5-logging/README.md
> Add note about initializing ADC.

- appengine-standard-java8/helloworld/pom.xml
- pom.xml
1. Move appengine-helloworld to first
2. Remove module from pom.xml where intellij was helping
> Move J8 HelloWorld to first

- appengine-standard-java8/helloworld/pom.xml
> Add region tags in pom.xml

- appengine-standard-java8/springboot-appengine-standard/pom.xml
https://github.com/GoogleCloudPlatform/getting-started-java/issues/257
> upgrading to v1.5.6.RELEASE

- appengine-standard-java8/kotlin-spark-appengine-standard/pom.xml
slf4j-api appears to have changed from 1.7.25 -> 1.8
> revert slf4j

- helloworld-springboot/pom.xml
- pom.xml
1. turn testing back on for Spring-Boot.
2. Update to latest
Fixes #294 #228 #84 #135
> spring-boot

- flexible/tomcat/helloworld/pom.xml
1. Move versions from properties to inline
2. add a version to cargo
> fix versions

- flexible/tomcat/helloworld/pom.xml
> Add a few tags

- bookshelf/README.md
> MVMs are the old name

- appengine-standard-java8/helloworld-gae-javasdk-tools/src/main/webapp/index.jsp
changed the import statement for the HelloAppEngine
> corrected the import statement

- .kokoro/tests/diff_tests.sh
fix bash error for comparing files
> Update Kokoro diff testing file

- bookshelf/1-cloud-run/README.md
- bookshelf/1-cloud-run/pom.xml
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/basicactions/CreateBookServlet.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/basicactions/DeleteBookServlet.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/basicactions/ListBookServlet.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/basicactions/ReadBookServlet.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/basicactions/UpdateBookServlet.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/daos/BookDao.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/daos/FirestoreDao.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/objects/Book.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/objects/Result.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/util/BookDaoContextListener.java
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/util/CloudStorageHelper.java
- bookshelf/1-cloud-run/src/main/resources/application.properties
- bookshelf/1-cloud-run/src/main/webapp/base.jsp
- bookshelf/1-cloud-run/src/main/webapp/form.jsp
- bookshelf/1-cloud-run/src/main/webapp/list.jsp
- bookshelf/1-cloud-run/src/main/webapp/view.jsp
- bookshelf/1-cloud-run/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/1-single-page/src/main/java/com/example/getstarted/Main.java
- bookshelf/2-structured-data/pom.xml
- bookshelf/3-binary-data/pom.xml
- bookshelf/4-auth/pom.xml
- bookshelf/5-logging/pom.xml
- bookshelf/pom.xml
- helloworld-springboot/pom.xml
So that we don't have to use AppEngine Flex in getting-started.
Things that are copied directly without changes from 1-single-page:
* All Java code
* All jsp
Things that are copied with changes:
* pom.xml
* README.md
New things:
* Dockerfile
> Cloud Run bookshelf example.

- renovate.json
@kurtisvg PTAL - I'm going to commit, but I'd like to review after the fact.
> make similar to j-d-s

- .github/blunderbuss.yml
- renovate.json
Add more folks to blunderbuss and remove troublesome renovate config.
> Update renovate.json and blunderbuss.yml

- background/pom.xml
- bookshelf/1-cloud-run/pom.xml
Odd that I need to create another branch for this.
> Renovate/com.google.cloud google cloud firestore 1.x

- background/pom.xml
- background/src/test/java/com/getstarted/background/UserJourneyTestIT.java
- bookshelf-standard/2-structured-data/pom.xml
- bookshelf-standard/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/3-binary-data/pom.xml
- bookshelf-standard/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/4-auth/pom.xml
- bookshelf-standard/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/5-logging/pom.xml
- bookshelf-standard/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf-standard/pom.xml
- bookshelf/1-cloud-run/pom.xml
- bookshelf/1-cloud-run/src/main/java/com/example/getstarted/util/BookshelfContextListener.java
- bookshelf/1-cloud-run/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/2-structured-data/pom.xml
- bookshelf/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/3-binary-data/pom.xml
- bookshelf/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/4-auth/pom.xml
- bookshelf/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/5-logging/pom.xml
- bookshelf/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
- bookshelf/pom.xml
> Renovate/org.seleniumhq.selenium selenium server 3.x

- renovate.json
> Some packages should update together

- gce/pom.xml
> Remove deprecated gcloud-java dependency from gce.

- .kokoro/tests/run_tests.sh
Fix: https://github.com/GoogleCloudPlatform/getting-started-java/issues/581
> enable build cop bot

- pom.xml
Causing getting-started-java periodic tests to fail on go/fusion.
> Remove deleted modules from parent pom.xml.

- appengine-standard-java8/helloworld-gae-javasdk-tools/README.md
- appengine-standard-java8/helloworld-gae-javasdk-tools/pom.xml
- appengine-standard-java8/kotlin-appengine-standard/README.md
- appengine-standard-java8/kotlin-sb-appengine-standard/README.md
- appengine-standard-java8/kotlin-spark-appengine-standard/README.md
- bookshelf-standard/2-structured-data/README.md
- bookshelf-standard/3-binary-data/README.md
- bookshelf-standard/4-auth/README.md
- bookshelf-standard/5-logging/README.md
- bookshelf/2-structured-data/README.md
- bookshelf/3-binary-data/README.md
- bookshelf/4-auth/README.md
- bookshelf/5-logging/README.md
- helloworld-jsp/README.md
- helloworld-jsp/build.gradle
- helloworld-jsp/pom.xml
> Update appengine plugin version

- background/src/main/java/com/getstarted/background/util/BackgroundContextListener.java
> fix: switch ProjectTopicName to TopicName

- gce/scripts/startup-script.sh
Fixes b/207372564
Followed https://cloud.google.com/logging/docs/agent/logging/installation#joint-install
> fix: update curl | bash

- bookshelf/1-cloud-run/README.md
- bookshelf/1-cloud-run/pom.xml
- bookshelf/1-cloud-run/src/main/webapp/WEB-INF/web.xml
> fix: update cloud run sample
